############################################################
# +------------------------------------------------------+ #
# |                      MultiChat                       | #
# +------------------------------------------------------+ #
############################################################

# By Revilo410

##################
#   DON'T EDIT   #
version: "1.7.3" #
##################

# 1. General
# 2. Private Messaging
# 3. Global Chat
# 4. Group Chats
# 5. Staff Chats
# 6. Other

############################################################
# +------------------------------------------------------+ #
# |                       General                        | #
# +------------------------------------------------------+ #
############################################################

# Should MultiChat fetch the display names from players respective spigot servers rather than those set on bungeecord to use in the global chat?
# Set this to true if you want to use display names set by plugins such as Essentials, Vault etc.
# If you want to use display names set by a bungeecord plugin such as BungeePerms then set this to false.
# PLEASE NOTE THAT IF THIS IS SET TO TRUE, CHAT WILL ONLY WORK IF YOU ALSO PUT THE MULTICHAT.JAR IN THE SPIGOT SERVERS PLUGIN FOLDERS AS WELL
# AS IN THE BUNGEECORD PLUGINS FOLDER!
fetch_spigot_display_names: true

# Should MultiChat set the display name of users to be used in things like the tab list and /glist?
set_display_name: true

# Display name format
# You can use %NAME% %NICK% %PREFIX% %SUFFIX%
display_name_format: "%PREFIX%%NICK%%SUFFIX%"

############################################################
# +------------------------------------------------------+ #
# |                  Private Messaging                   | #
# +------------------------------------------------------+ #
############################################################

#############
# PM MODULE #
#############

# Use private messaging?
pm: true

# Servers to exclude from private messaging
# List like:
# no_pm:
# - Server1
# - Server2
# etc.

no_pm: []

# Allow players to toggle PMs by just typing /msg <playername>
toggle_pm: true

##############
# PM FORMATS #
##############

# USES STANDARD MINECRAFT '&X' COLOUR/FORMAT CODES
# %MESSAGE% = The sent message
# %NAME% = The name of the sender
# %NAMET% = The name of the target player
# %DISPLAYNAME% = The display name of the sender
# %DISPLAYNAMET% = The display name of the target player
# %PREFIX% = The prefix of the sender
# %PREFIXT% = The prefix of the target
# %SUFFIX% = The suffix of the sender
# %SUFFIXT% = The suffix of the target
# %NICK% = The nickname of the sender
# %NICKT% = The nickname of the target
# %SERVER% = The server of the sender
# %SERVERT% = The server of the target player
# %WORLD% = The world of the sender
# %WORLDT% = The world of the target player

# Sending PM Format

pmout: "&6[&cYou &6-> &c%DISPLAYNAMET%&6] &f%MESSAGE%"

# Receving PM Format

pmin: "&6[&c%DISPLAYNAME% &6-> &cMe&6] &f%MESSAGE%"

# SocialSpy Format

pmspy: "&8&l<< &f%NAME% &7-> &f%NAMET%&8: &7%MESSAGE% &8&l>>"

##############
# PM ALIASES #
##############

# The /msg command has the following aliases (other than /msg)
msgcommand:
- m
- message
- t
- tell
- w
- whisper
- chat
- pm

# The /r command has the following aliases (other than /r)
rcommand:
- reply
- respond

# The /socialspy command has the following aliases (other than /socialspy)
socialspycommand:
- spy
- sspy

############################################################
# +------------------------------------------------------+ #
# |                    Chat Channels                     | #
# +------------------------------------------------------+ #
############################################################

# The default chat channel that players will be assigned when they first join
# Must be "local" or "global", if anything else is specified then will default to "global"
default_channel: "global"

# Force players into default channel when they join the server?
force_channel_on_join: false

# The /channel command has the following aliases (other than /channel)
channelcommand:
- ch

############################################################
# +------------------------------------------------------+ #
# |                     Global Chat                      | #
# +------------------------------------------------------+ #
############################################################

######################
# Global Chat Module #
######################

# Use global public chat?
global: true

# Servers to exclude from global chat
# List like:
# no_global:
# - Server1
# - Server2
# etc.

no_global: []

#######################
# Global Chat Formats #
#######################

# USES STANDARD MINECRAFT '&X' COLOUR/FORMAT CODES
# %NAME% = The name of the sender
# %DISPLAYNAME% = The display name of the sender
# %PREFIX% = The prefix of the sender
# %SUFFIX% = The suffix of the sender
# %NICK% = The nickname of the sender
# %SERVER% = The server of the sender
# %WORLD% = The world of the sender

# Global Chat Format
# Will display as [FORMAT] [MESSAGE]

globalformat: "&2[&aG&2] &f%DISPLAYNAME%&f: "

############################################################
# +------------------------------------------------------+ #
# |                     Group Chats                      | #
# +------------------------------------------------------+ #
############################################################

######################
# Group Chat Formats #
######################

# USES STANDARD MINECRAFT '&X' COLOUR/FORMAT CODES
# %NAME% = The name of the sender
# %MESSAGE% = The sent message
# %CC% = The chat color set by players
# %NC% = The name color set by players
# %GROUPNAME% = Name of the group chat

groupchat:
    format: "%CC%(%NC%%GROUPNAME%%CC%)(%NC%%NAME%%CC%) %MESSAGE%"
    ccdefault: "a"
    ncdefault: "f"

############################################################
# +------------------------------------------------------+ #
# |                     Staff Chats                      | #
# +------------------------------------------------------+ #
############################################################

######################
# Staff Chat Formats #
######################

# USES STANDARD MINECRAFT '&X' COLOUR/FORMAT CODES
# %NAME% = The name of the sender
# %DISPLAYNAME% = The display name of the sender
# %SERVER% = The server of the sender
# %WORLD% = The world of the sender
# %MESSAGE% = The sent message
# %CC% = The chat color set by players
# %NC% = The name color set by players

modchat:
    format: "%CC%{%NC%%NAME%%CC%} %MESSAGE%"
    ccdefault: "b"
    ncdefault: "d"

adminchat:
    format: "%CC%{%NC%%NAME%%CC%} %MESSAGE%"
    ccdefault: "d"
    ncdefault: "b"

############################################################
# +------------------------------------------------------+ #
# |                        Other                         | #
# +------------------------------------------------------+ #
############################################################

# Set to false to disable the '/staff' staff list command
staff_list: true

# MultiChat bypass command aliases (other than /multichatbypass)
multichatbypasscommand:
- mcb
- bypass

# MultiChat execute command aliases (other than /multichatexecute)
multichatexecutecommand:
- mcexecute
- mce
- gexecute
- gexe
- gcommand
